cert-manager:
  installCRDs: true
  
  global:
    leaderElection:
      namespace: cert-manager
  
  # Ensure cert-manager can manage certificates cluster-wide
  extraArgs:
    - --cluster-resource-namespace=cert-manager
    - --leader-election-namespace=cert-manager